collections:
  tags:
    output: true

permalink: pretty

defaults:
  - scope:
      path: ""
      type: "tags"
    values:
      layout: "tagpage"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"